<#
.SYNOPSIS
Interactive Bundlr + anchoring environment setup.

This does THREE things:
1) Checks that the Bundlr CLI is available on PATH ("bundlr").
2) Prompts you for Bundlr settings (currency, node URL, keyfile).
3) Sets environment variables AND writes them to env/bundlr.env.ps1
   so you can re-load them later with a single command.

It does NOT perform any live uploads.
#>

param(
    # "dev" = safe default (no live anchoring, even if you fat-finger -Live)
    # "prod" = only use when you are genuinely ready to anchor for real.
    [ValidateSet("dev","prod")]
    [string]$AnchorEnv = "dev"
)

Write-Host "=== SOVEREIGN ANCHOR ENV SETUP ===" -ForegroundColor Cyan
Write-Host "AnchorEnv  : $AnchorEnv" -ForegroundColor Yellow
Write-Host ""

# 1) Check Bundlr CLI
Write-Host "[1/4] Checking for Bundlr CLI (command: 'bundlr')..." -ForegroundColor Cyan
$bundlrCmd = Get-Command bundlr -ErrorAction SilentlyContinue

if (-not $bundlrCmd) {
    Write-Error "Bundlr CLI not found on PATH. Install it (e.g. 'npm install -g @bundlr-network/client' or your provider's CLI) and retry."
    return
}

Write-Host "Bundlr CLI found at: $($bundlrCmd.Source)" -ForegroundColor Green
Write-Host ""

# 2) Collect Bundlr settings
Write-Host "[2/4] Enter Bundlr settings" -ForegroundColor Cyan

# Default guesses – CHANGE these to whatever your actual provider gave you
$defaultCurrency = if ($env:BUNDLR_CURRENCY) { $env:BUNDLR_CURRENCY } else { "ar" }
$defaultNodeUrl  = if ($env:BUNDLR_NODE_URL)  { $env:BUNDLR_NODE_URL }  else { "https://node1.bundlr.network" }

$currency = Read-Host "Bundlr currency code (e.g. ar, solana, matic) [$defaultCurrency]"
if ([string]::IsNullOrWhiteSpace($currency)) { $currency = $defaultCurrency }

$nodeUrl = Read-Host "Bundlr node URL [$defaultNodeUrl]"
if ([string]::IsNullOrWhiteSpace($nodeUrl)) { $nodeUrl = $defaultNodeUrl }

$keyPath = Read-Host "Full path to Bundlr wallet/keyfile (JSON, from provider)"
if (-not (Test-Path $keyPath)) {
    Write-Error "Key file not found at: $keyPath"
    return
}

Write-Host ""
Write-Host "You entered:" -ForegroundColor Yellow
Write-Host "  AnchorEnv       : $AnchorEnv"
Write-Host "  BUNDLR_CURRENCY : $currency"
Write-Host "  BUNDLR_NODE_URL : $nodeUrl"
Write-Host "  BUNDLR_KEYFILE  : $keyPath"
Write-Host ""

$confirm = Read-Host "Proceed with these settings? (y/n)"
if ($confirm -ne 'y' -and $confirm -ne 'Y') {
    Write-Host "Aborted by user." -ForegroundColor DarkYellow
    return
}

# 3) Set environment variables for THIS SESSION
Write-Host "[3/4] Setting environment variables for this session..." -ForegroundColor Cyan

$env:ANCHOR_ENV      = $AnchorEnv
$env:BUNDLR_CURRENCY = $currency
$env:BUNDLR_NODE_URL = $nodeUrl
$env:BUNDLR_KEYFILE  = $keyPath

Write-Host "Session env set." -ForegroundColor Green

# 4) Persist settings to env/bundlr.env.ps1 for easy reload
Write-Host "[4/4] Writing env/bundlr.env.ps1 for future sessions..." -ForegroundColor Cyan

$envDir = Join-Path $PSScriptRoot "..\env"
if (-not (Test-Path $envDir)) {
    New-Item -ItemType Directory -Force -Path $envDir | Out-Null
}

$envFile = Join-Path $envDir "bundlr.env.ps1"

@"
# Auto-generated by Setup-BundlrEnv.ps1
# Dot-source this file from PowerShell to restore your Bundlr + anchor env:
#   . `"$envFile`"

`$env:ANCHOR_ENV      = '$AnchorEnv'
`$env:BUNDLR_CURRENCY = '$currency'
`$env:BUNDLR_NODE_URL = '$nodeUrl'
`$env:BUNDLR_KEYFILE  = '$keyPath'
"@ | Set-Content -LiteralPath $envFile -Encoding UTF8

Write-Host "Env file written to: $envFile" -ForegroundColor Green

Write-Host ""
Write-Host "=== QUICK TEST (DRY ONLY) ===" -ForegroundColor Cyan
Write-Host "Run something like:" -ForegroundColor Yellow
Write-Host "  . `"$envFile`"" -ForegroundColor Gray
Write-Host "  bundlr balance -c $currency -h $nodeUrl" -ForegroundColor Gray
Write-Host ""
Write-Host "To run DRY-RUN anchoring:" -ForegroundColor Yellow
Write-Host "  . `"$envFile`"" -ForegroundColor Gray
Write-Host "  cd C:\Users\andyj\source\repos\PrecisePointway\master" -ForegroundColor Gray
Write-Host "  .\scripts\Perform-NetworkAnchoring.ps1 -ManifestPath <manifest.json>" -ForegroundColor Gray
Write-Host ""
Write-Host "To enable LIVE anchoring later, re-run this script with -AnchorEnv prod and use -Live flag:" -ForegroundColor Yellow
Write-Host "  .\scripts\Setup-BundlrEnv.ps1 -AnchorEnv prod" -ForegroundColor Gray
Write-Host "  . `"$envFile`"" -ForegroundColor Gray
Write-Host "  .\scripts\Perform-NetworkAnchoring.ps1 -ManifestPath <manifest.json> -Live" -ForegroundColor Gray
Write-Host ""
Write-Host "SOVEREIGN NOTE: LIVE mode only happens when BOTH ANCHOR_ENV=prod AND -Live are present." -ForegroundColor Cyan
